// Generated by tools/obfuscate_edge_e3.py; do not edit.

module fpga_ram(
  PortAClk,
  PortAAddr,
  PortADataIn,
  PortAWriteEnable,

  PortADataOut
);

parameter  DATAWIDTH = 2;
parameter  ADDRWIDTH = 2;

input                     PortAClk;
input   [(ADDRWIDTH-1):0] PortAAddr;
input   [(DATAWIDTH-1):0] PortADataIn;
input                     PortAWriteEnable;

output  [(DATAWIDTH-1):0] PortADataOut;

parameter  MEMDEPTH = 2**(ADDRWIDTH);

reg [(DATAWIDTH-1):0] xa11ff4ee0e4c1b3e [(MEMDEPTH-1):0] /* synthesis syn_ramstyle = "no_rw_check" */;
reg [(DATAWIDTH-1):0] PortADataOut;

always @(posedge PortAClk)
begin
  if(PortAWriteEnable)
  begin
    xa11ff4ee0e4c1b3e[PortAAddr]  <= PortADataIn;
    PortADataOut    <= PortADataIn;
  end
  else
  begin
    PortADataOut    <= xa11ff4ee0e4c1b3e[PortAAddr];
  end
end















endmodule


module edge_f_spsram_1024x64(
  A,
  CEN,
  CLK,
  D,
  GWEN,
  Q,
  WEN
);

parameter ADDR_WIDTH = 10;
parameter DATA_WIDTH = 64;
parameter WRAP_SIZE  = 1;

input  [ADDR_WIDTH-1:0]   A;
input                     CEN;
input                     CLK;
input  [DATA_WIDTH-1:0]   D;
input                     GWEN;
input  [DATA_WIDTH-1:0]   WEN;
output [DATA_WIDTH-1:0]   Q;

reg    [ADDR_WIDTH-1:0]   xe8fd2bbbe6fdce79;

wire  [ADDR_WIDTH-1:0]   A;
wire                     CEN;
wire                     CLK;
wire  [DATA_WIDTH-1:0]   D;
wire                     GWEN;
wire  [DATA_WIDTH-1:0]   WEN;
wire  [DATA_WIDTH-1:0]   Q;
wire  [ADDR_WIDTH-1:0]   xa27010bc37f9ec4a;

always@(posedge CLK)
begin
  if(!CEN) begin
    xe8fd2bbbe6fdce79[ADDR_WIDTH-1:0] <= A[ADDR_WIDTH-1:0];
  end
end

assign xa27010bc37f9ec4a[ADDR_WIDTH-1:0] = CEN ? xe8fd2bbbe6fdce79[ADDR_WIDTH-1:0]
                                  : A[ADDR_WIDTH-1:0];

wire [DATA_WIDTH-1:0] xafd4c50fdd24b1be;
genvar x5ce21f903fc5ffc6;
generate
  for(x5ce21f903fc5ffc6=0; x5ce21f903fc5ffc6<DATA_WIDTH; x5ce21f903fc5ffc6=x5ce21f903fc5ffc6+1) begin: x4d303c699b4a775b
    assign xafd4c50fdd24b1be[x5ce21f903fc5ffc6] = !CEN & !WEN[x5ce21f903fc5ffc6]  & !GWEN;
    fpga_ram #(WRAP_SIZE,ADDR_WIDTH) xe4f6372d989ebc1a(
      .PortAClk (CLK),
      .PortAAddr(xa27010bc37f9ec4a),
      .PortADataIn (D[x5ce21f903fc5ffc6]),
      .PortAWriteEnable(xafd4c50fdd24b1be[x5ce21f903fc5ffc6]),
      .PortADataOut(Q[x5ce21f903fc5ffc6]));
  end
endgenerate

endmodule




module edge_spsram_1024x64(
  A,
  CEN,
  CLK,
  D,
  GWEN,
  Q,
  WEN
);


input   [9 :0]  A;
input           CEN;
input           CLK;
input   [63:0]  D;
input           GWEN;
input   [63:0]  WEN;
output  [63:0]  Q;




wire    [9 :0]  A;
wire            CEN;
wire            CLK;
wire    [63:0]  D;
wire            GWEN;
wire    [63:0]  Q;
wire    [63:0]  WEN;





parameter ADDR_WIDTH = 10;
parameter DATA_WIDTH = 64;
parameter WE_WIDTH   = 64;










edge_f_spsram_1024x64  x9e26000aab0c2564 (
  .A    (A   ),
  .CEN  (CEN ),
  .CLK  (CLK ),
  .D    (D   ),
  .GWEN (GWEN),
  .Q    (Q   ),
  .WEN  (WEN )
);




endmodule





module edge_dtcm_spsram_1024x64(
  A,
  CEN,
  CLK,
  D,
  GWEN,
  Q,
  WEN
);

parameter ADDR_WIDTH = 10;
parameter DATA_WIDTH = 64;
parameter BYTE_WIDTH = DATA_WIDTH / 8;

input  [ADDR_WIDTH-1:0] A;
input                   CEN;
input                   CLK;
input  [DATA_WIDTH-1:0] D;
input                   GWEN;
input  [DATA_WIDTH-1:0] WEN;
output [DATA_WIDTH-1:0] Q;

reg [DATA_WIDTH-1:0] Q;

(* x9e49fcf55628bd9c = "block" *)
reg [DATA_WIDTH-1:0] xa11ff4ee0e4c1b3e [0:(1 << ADDR_WIDTH)-1];

integer x45a146416dbca747;

always @(posedge CLK) begin
  if (!CEN) begin
    Q[DATA_WIDTH-1:0] <= xa11ff4ee0e4c1b3e[A[ADDR_WIDTH-1:0]];

    if (!GWEN) begin
      for (x45a146416dbca747 = 0; x45a146416dbca747 < BYTE_WIDTH; x45a146416dbca747 = x45a146416dbca747 + 1) begin
        if (WEN[x45a146416dbca747*8 +: 8] != 8'hff)
          xa11ff4ee0e4c1b3e[A[ADDR_WIDTH-1:0]][x45a146416dbca747*8 +: 8] <=
            D[x45a146416dbca747*8 +: 8];
      end
    end
  end
end

endmodule


